### PR TITLE
Create an entry point in reductio API for custom reducers

### PR DESCRIPTION
**Pull request by alemarre**
Hi,

I have a complex case in my dataset that i can't handle with the native reducers included in reductio.
(even if the list is pretty large, thanks for all this work btw)

I suggest to add an entry point for custom reducers in your API, it would allow to plug any custom extension.

Could you please check this pull request ? Don't hesitate to tell me if you see anything wrong :)

Thanks

### CODE REVIEW

**Comment by esjewett** [comment]
Hi,

a) I've been meaning to do this for ages so it's great to get a pull request for this improvement
b) It looks good to me at first glance

I'm going to look at it a little more carefully and then I plan to merge it.

However, would you mind updating the documentation in the README as part of this pull request? Just update the README.md file directly.

Thank you!
Ethan

**Comment by alemarre** [comment]
Hi,

I have updated the doc.
Thanks for the review

Armand

**Comment by esjewett** [comment]
Thanks for the contribution! I will try to cut release 0.6.0 today with this functionality.

**Comment by alemarre** [comment]
Great, thanks for your rapidity !

**Pull request merged**
