### PR TITLE
Updating crossfilter to v1.4.1.

### PR DESCRIPTION
**Pull request by saboya**

### CODE REVIEW

**Comment by esjewett** [comment]
Hi - I appreciate the pull request. Question for you: Is this necessary? It looks to me like just doing `npm install reductio` will pull the latest version of `crossfilter2` by default. When you sent this it was 1.4.1, but it is now 1.4.2. My understanding was that `^1.4.0` means "most recent version higher than `1.4.0`".

Thoughts on that? Anything else that needs to change or that I'm missing? I really not an expert on NPM versioning, so it's quite possible I'm getting something wrong. Thanks!

**Comment by saboya** [comment]
You are correct, I am merely bumping the version. I'm not 100% sure about how npm versioning works when installing the package, but maybe because of the particular version chosen (an alpha version), my bundle ends up with multiple crossfilter versions if I install reductio alongside crossfilter 1.4.1, and that's my reasoning behind the PR.

Regards!

**Comment by esjewett** [comment]
Weird - but ok, that makes some sense that it wouldn't jump from alpha versions to "real" versions. Can you change it to require ^1.4.0 and then I'll merge this? Thanks!

**Comment by saboya** [comment]
Done!

**Comment by esjewett** [comment]
Will target 0.6.4, but will likely wait until we need a release for another reason. Let me know if this continues to cause problems in a clean installation scenario.

**Pull request merged**
